//Функция для возвращения ошибки
export default function throwFetchError(message) {
    throw new Error(message)
}
